"""initial_schema_v2

Revision ID: 36f2a2b8b6f3
Revises: 
Create Date: 2026-05-03 06:13:12.470450+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f2a2b8b6f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpt_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('base_rvu', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpt_codes_code'), 'cpt_codes', ['code'], unique=True)
    op.create_index(op.f('ix_cpt_codes_id'), 'cpt_codes', ['id'], unique=False)
    op.create_table('icd10_codes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_billable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icd10_codes_code'), 'icd10_codes', ['code'], unique=True)
    op.create_index(op.f('ix_icd10_codes_id'), 'icd10_codes', ['id'], unique=False)
    op.create_table('ncci_edits',
    sa.Column('code_1', sa.String(length=20), nullable=False),
    sa.Column('code_2', sa.String(length=20), nullable=False),
    sa.Column('modifier_allowed', sa.Boolean(), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ncci_edits_code_1'), 'ncci_edits', ['code_1'], unique=False)
    op.create_index(op.f('ix_ncci_edits_code_2'), 'ncci_edits', ['code_2'], unique=False)
    op.create_index(op.f('ix_ncci_edits_id'), 'ncci_edits', ['id'], unique=False)
    op.create_table('payers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('payer_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payers_id'), 'payers', ['id'], unique=False)
    op.create_index(op.f('ix_payers_payer_id'), 'payers', ['payer_id'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('branding_logo_url', sa.String(length=1024), nullable=True),
    sa.Column('branding_primary_color', sa.String(length=20), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_domain'), 'tenants', ['domain'], unique=True)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_table('payer_rules',
    sa.Column('payer_id', sa.String(length=50), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('cpt_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.payer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payer_rules_cpt_code'), 'payer_rules', ['cpt_code'], unique=False)
    op.create_index(op.f('ix_payer_rules_id'), 'payer_rules', ['id'], unique=False)
    op.create_index(op.f('ix_payer_rules_rule_code'), 'payer_rules', ['rule_code'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_payer_rules_rule_code'), table_name='payer_rules')
    op.drop_index(op.f('ix_payer_rules_id'), table_name='payer_rules')
    op.drop_index(op.f('ix_payer_rules_cpt_code'), table_name='payer_rules')
    op.drop_table('payer_rules')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_domain'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_payers_payer_id'), table_name='payers')
    op.drop_index(op.f('ix_payers_id'), table_name='payers')
    op.drop_table('payers')
    op.drop_index(op.f('ix_ncci_edits_id'), table_name='ncci_edits')
    op.drop_index(op.f('ix_ncci_edits_code_2'), table_name='ncci_edits')
    op.drop_index(op.f('ix_ncci_edits_code_1'), table_name='ncci_edits')
    op.drop_table('ncci_edits')
    op.drop_index(op.f('ix_icd10_codes_id'), table_name='icd10_codes')
    op.drop_index(op.f('ix_icd10_codes_code'), table_name='icd10_codes')
    op.drop_table('icd10_codes')
    op.drop_index(op.f('ix_cpt_codes_id'), table_name='cpt_codes')
    op.drop_index(op.f('ix_cpt_codes_code'), table_name='cpt_codes')
    op.drop_table('cpt_codes')
    # ### end Alembic commands ###
