"""add_appeal_models

Revision ID: f54ccaf80d8d
Revises: 5cbeed2d02c1
Create Date: 2026-05-03 09:23:10.007476+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f54ccaf80d8d'
down_revision: Union[str, None] = '5cbeed2d02c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('claim_id', sa.String(length=100), nullable=False),
    sa.Column('encounter_id', sa.String(length=100), nullable=False),
    sa.Column('denial_reason_codes', sa.JSON(), nullable=False),
    sa.Column('original_codes', sa.JSON(), nullable=False),
    sa.Column('appeal_letter_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appeals_claim_id'), 'appeals', ['claim_id'], unique=False)
    op.create_index(op.f('ix_appeals_encounter_id'), 'appeals', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_appeals_id'), 'appeals', ['id'], unique=False)
    op.create_index(op.f('ix_appeals_tenant_id'), 'appeals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appeals_tenant_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_encounter_id'), table_name='appeals')
    op.drop_index(op.f('ix_appeals_claim_id'), table_name='appeals')
    op.drop_table('appeals')
    # ### end Alembic commands ###
