"""add_claim_models

Revision ID: f7795ab4e170
Revises: 03eccb874b05
Create Date: 2026-05-03 09:15:06.016776+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7795ab4e170'
down_revision: Union[str, None] = '03eccb874b05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('encounter_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('icd10_codes', sa.JSON(), nullable=False),
    sa.Column('cpt_codes', sa.JSON(), nullable=False),
    sa.Column('modifiers', sa.JSON(), nullable=True),
    sa.Column('total_charge', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('clearinghouse_claim_id', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_encounter_id'), 'claims', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_patient_id'), 'claims', ['patient_id'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_patient_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_encounter_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
