"""add_intake_models

Revision ID: 03eccb874b05
Revises: 7b7d468c8863
Create Date: 2026-05-03 09:11:18.861665+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03eccb874b05'
down_revision: Union[str, None] = '7b7d468c8863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_intakes',
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('encounter_id', sa.String(length=100), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_service', sa.String(length=20), nullable=True),
    sa.Column('eligibility_status', sa.String(length=50), nullable=True),
    sa.Column('eligibility_raw_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_intakes_encounter_id'), 'patient_intakes', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_patient_intakes_id'), 'patient_intakes', ['id'], unique=False)
    op.create_index(op.f('ix_patient_intakes_patient_id'), 'patient_intakes', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_intakes_tenant_id'), 'patient_intakes', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_intakes_tenant_id'), table_name='patient_intakes')
    op.drop_index(op.f('ix_patient_intakes_patient_id'), table_name='patient_intakes')
    op.drop_index(op.f('ix_patient_intakes_id'), table_name='patient_intakes')
    op.drop_index(op.f('ix_patient_intakes_encounter_id'), table_name='patient_intakes')
    op.drop_table('patient_intakes')
    # ### end Alembic commands ###
