"""add_payment_models

Revision ID: 5cbeed2d02c1
Revises: f7795ab4e170
Create Date: 2026-05-03 09:19:35.440932+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbeed2d02c1'
down_revision: Union[str, None] = 'f7795ab4e170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('claim_id', sa.String(length=100), nullable=False),
    sa.Column('encounter_id', sa.String(length=100), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('patient_responsibility', sa.Float(), nullable=True),
    sa.Column('adjustment_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('adjustment_codes', sa.JSON(), nullable=True),
    sa.Column('remittance_date', sa.DateTime(), nullable=True),
    sa.Column('raw_era_data', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_claim_id'), 'payments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_payments_encounter_id'), 'payments', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_encounter_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_claim_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
