"""add_learning_models

Revision ID: 7b7d468c8863
Revises: 36f2a2b8b6f3
Create Date: 2026-05-03 06:24:32.993138+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7d468c8863'
down_revision: Union[str, None] = '36f2a2b8b6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_history',
    sa.Column('encounter_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=False),
    sa.Column('clinical_note', sa.Text(), nullable=False),
    sa.Column('ai_suggested_codes', sa.JSON(), nullable=False),
    sa.Column('ai_confidence_score', sa.Float(), nullable=False),
    sa.Column('ai_audit_trail', sa.JSON(), nullable=True),
    sa.Column('human_approved_codes', sa.JSON(), nullable=True),
    sa.Column('is_human_edited', sa.Boolean(), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coding_history_encounter_id'), 'coding_history', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_coding_history_id'), 'coding_history', ['id'], unique=False)
    op.create_index(op.f('ix_coding_history_patient_id'), 'coding_history', ['patient_id'], unique=False)
    op.create_index(op.f('ix_coding_history_tenant_id'), 'coding_history', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coding_history_tenant_id'), table_name='coding_history')
    op.drop_index(op.f('ix_coding_history_patient_id'), table_name='coding_history')
    op.drop_index(op.f('ix_coding_history_id'), table_name='coding_history')
    op.drop_index(op.f('ix_coding_history_encounter_id'), table_name='coding_history')
    op.drop_table('coding_history')
    # ### end Alembic commands ###
